/*
  Auditoria focada: FINANCING_CONDITIONS / INTEREST_RATES_ARRAY no legado (PRE_ANALYSIS_TYPE='pre_analysis')

  Objetivo:
    - Confirmar se os campos existem e qual o TYPEOF (OBJECT vs ARRAY).
    - Medir fill-rate e "tamanho" (n de ofertas) por mês.
    - Inspecionar exemplos reais para ajustar o parser do enrichment.
*/

/* [1/2] Profile por mês */
WITH params AS (
  SELECT 18::INT AS months_back
),
base AS (
  SELECT
    pa.PRE_ANALYSIS_ID,
    pa.PRE_ANALYSIS_CREATED_AT,
    pa.MINIMUM_TERM_AVAILABLE,
    pa.MAXIMUM_TERM_AVAILABLE,
    pa.FINANCING_CONDITIONS,
    pa.INTEREST_RATES_ARRAY
  FROM CAPIM_DATA.CAPIM_ANALYTICS.PRE_ANALYSES pa
  JOIN params p ON TRUE
  WHERE pa.PRE_ANALYSIS_TYPE = 'pre_analysis'
    AND pa.PRE_ANALYSIS_CREATED_AT >= DATEADD('month', -p.months_back, DATE_TRUNC('month', CURRENT_DATE()))
)
SELECT
  DATE_TRUNC('month', PRE_ANALYSIS_CREATED_AT) AS month,
  COUNT(*)::NUMBER AS n_rows,
  COUNT_IF(FINANCING_CONDITIONS IS NOT NULL) AS n_financing_nonnull,
  COUNT_IF(INTEREST_RATES_ARRAY IS NOT NULL) AS n_interest_rates_nonnull,
  COUNT_IF(TYPEOF(FINANCING_CONDITIONS)='OBJECT') AS n_financing_object,
  COUNT_IF(TYPEOF(FINANCING_CONDITIONS)='ARRAY')  AS n_financing_array,
  COUNT_IF(TYPEOF(FINANCING_CONDITIONS) NOT IN ('OBJECT','ARRAY') AND FINANCING_CONDITIONS IS NOT NULL) AS n_financing_other,
  COUNT_IF(TYPEOF(INTEREST_RATES_ARRAY)='OBJECT') AS n_ir_object,
  COUNT_IF(TYPEOF(INTEREST_RATES_ARRAY)='ARRAY')  AS n_ir_array,
  COUNT_IF(TYPEOF(INTEREST_RATES_ARRAY) NOT IN ('OBJECT','ARRAY') AND INTEREST_RATES_ARRAY IS NOT NULL) AS n_ir_other,
  COUNT_IF(MINIMUM_TERM_AVAILABLE IS NOT NULL) AS n_min_term_available,
  COUNT_IF(MAXIMUM_TERM_AVAILABLE IS NOT NULL) AS n_max_term_available
FROM base
GROUP BY 1
ORDER BY 1
;

/* [2/2] Exemplos (para inspecionar o formato real) */
WITH params AS (
  SELECT
    18::INT AS months_back,
    25::INT AS sample_n
),
base AS (
  SELECT
    pa.PRE_ANALYSIS_ID,
    pa.PRE_ANALYSIS_CREATED_AT,
    pa.PRE_ANALYSIS_STATE,
    pa.MINIMUM_TERM_AVAILABLE,
    pa.MAXIMUM_TERM_AVAILABLE,
    pa.FINANCING_CONDITIONS,
    pa.INTEREST_RATES_ARRAY
  FROM CAPIM_DATA.CAPIM_ANALYTICS.PRE_ANALYSES pa
  JOIN params p ON TRUE
  WHERE pa.PRE_ANALYSIS_TYPE = 'pre_analysis'
    AND pa.PRE_ANALYSIS_CREATED_AT >= DATEADD('month', -p.months_back, DATE_TRUNC('month', CURRENT_DATE()))
)
SELECT
  PRE_ANALYSIS_ID,
  PRE_ANALYSIS_CREATED_AT,
  PRE_ANALYSIS_STATE,
  MINIMUM_TERM_AVAILABLE,
  MAXIMUM_TERM_AVAILABLE,
  TYPEOF(FINANCING_CONDITIONS) AS financing_type,
  TYPEOF(INTEREST_RATES_ARRAY) AS interest_rates_type,
  IFF(TYPEOF(INTEREST_RATES_ARRAY)='OBJECT', ARRAY_SIZE(OBJECT_KEYS(INTEREST_RATES_ARRAY)), ARRAY_SIZE(INTEREST_RATES_ARRAY)) AS interest_rates_size,
  FINANCING_CONDITIONS,
  INTEREST_RATES_ARRAY
FROM base
QUALIFY ROW_NUMBER() OVER (ORDER BY PRE_ANALYSIS_CREATED_AT DESC) <= (SELECT sample_n FROM params)
ORDER BY PRE_ANALYSIS_CREATED_AT DESC
;

