/*
  Auditoria de comportamento de "risk" nas fontes conhecidas.
*/

/* [A] CREDIT_SIMULATIONS: PAYMENT_DEFAULT_RISK (range/outliers) */
SELECT
  COUNT(*)::NUMBER AS n,
  COUNT_IF(PAYMENT_DEFAULT_RISK IS NOT NULL)::NUMBER AS n_nonnull,
  MIN(PAYMENT_DEFAULT_RISK) AS min_v,
  APPROX_PERCENTILE(PAYMENT_DEFAULT_RISK, 0.50) AS p50,
  APPROX_PERCENTILE(PAYMENT_DEFAULT_RISK, 0.95) AS p95,
  APPROX_PERCENTILE(PAYMENT_DEFAULT_RISK, 0.99) AS p99,
  MAX(PAYMENT_DEFAULT_RISK) AS max_v
FROM CAPIM_DATA.CAPIM_PRODUCTION.CREDIT_SIMULATIONS
;

/* values mais comuns (se for discreto 0..5) */
SELECT
  PAYMENT_DEFAULT_RISK,
  COUNT(*)::NUMBER AS n
FROM CAPIM_DATA.CAPIM_PRODUCTION.CREDIT_SIMULATIONS
WHERE PAYMENT_DEFAULT_RISK IS NOT NULL
GROUP BY 1
ORDER BY n DESC
LIMIT 30
;

/* [B] PRE_ANALYSES: RISK_CAPIM / SUBCLASS (valores distintos e contagem) */
SELECT
  RISK_CAPIM,
  RISK_CAPIM_SUBCLASS,
  COUNT(*)::NUMBER AS n
FROM CAPIM_DATA.CAPIM_ANALYTICS.PRE_ANALYSES
WHERE PRE_ANALYSIS_TYPE='pre_analysis'
GROUP BY 1,2
ORDER BY n DESC
LIMIT 50
;

/* [C] PRE_ANALYSES: coerência de formato numérico (0..5,-1,9) se aplicável */
SELECT
  COUNT(*)::NUMBER AS n,
  COUNT_IF(TRY_TO_NUMBER(RISK_CAPIM) IS NOT NULL)::NUMBER AS n_numeric_like,
  COUNT_IF(TRY_TO_NUMBER(RISK_CAPIM) IN (-1,0,1,2,3,4,5,9))::NUMBER AS n_in_expected_set,
  COUNT_IF(TRY_TO_NUMBER(RISK_CAPIM) NOT IN (-1,0,1,2,3,4,5,9) AND TRY_TO_NUMBER(RISK_CAPIM) IS NOT NULL)::NUMBER AS n_numeric_outside_set
FROM CAPIM_DATA.CAPIM_ANALYTICS.PRE_ANALYSES
WHERE PRE_ANALYSIS_TYPE='pre_analysis'
;

